[build]
  publish = "doc/build"
  # https://github.com/netlify/build-image/issues/221#issuecomment-504385202
  # https://github.com/netlify/build-image/issues/221#issuecomment-644662189
  command = """
pip install -q poetry==1.2.2 &&
poetry install --extras doc &&
./dev.py doc
"""
