name: CI

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 17 * * *'

jobs:
  check_code_format:
    name: Check code format
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ./.github/workflows/common
      with:
        extras-param: '--extras format'

    - name: Check code format
      run: ./dev.py black-check

  check_types:
    name: Check types
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ./.github/workflows/common

    - name: Check types
      run: ./dev.py check-types

  check_lint:
    name: Check lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ./.github/workflows/common
      with:
        extras-param: '--extras lint'

    - name: Check lint
      run: ./dev.py lint

  run_tests:
    name: Run tests - Python ${{ matrix.python-version }}, NumPy ${{ matrix.numpy-version }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
            numpy-version: '1.26.4'
          - python-version: '3.11'
            numpy-version: '1.26.4'
          - python-version: '3.12'
            numpy-version: '1.26.4'
          - python-version: '3.11'
            numpy-version: '2.4.2'
          - python-version: '3.12'
            numpy-version: '2.4.2'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ./.github/workflows/common
      with:
        python-version: ${{ matrix.python-version }}
        numpy-version: ${{ matrix.numpy-version }}
        extras-param: '--extras test --extras obj --extras cli'

    - name: Run tests
      run: ./dev.py coverage

  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: ./.github/workflows/common
      with:
        extras-param: '--extras doc'

    - name: Build the package
      run: poetry build

    - name: Upload distributable
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifacts
        path: dist/

    - name: Build the documentation
      if: always()
      run: ./dev.py doc
